</$objtype/mkfile

TARG=\
	usbmouse\
#	readir\

HFILES=\
	../lib/usb.h\

LIB=../lib/usb.a$O

UPDATE=\
	$HFILES\
	${OFILES:%.$O=%.c}\
	mkfile\
	usbprinter\
	usbprobe\

BIN=/$objtype/bin/usb
</sys/src/cmd/mkmany

CFLAGS=-I../lib $CFLAGS

$LIB:
	cd ../lib
	mk install
	mk clean

$BIN/usbprinter: usbprinter
	cp -x $newprereq $target
$BIN/usbprobe: usbprobe
	cp -x $newprereq $target
